# Needed for the PHP module (not linking to php symbols that are there when loaded into php)
%define _disable_ld_no_undefined 1

Name:		gromox
Version:	3.5
Release:	2
Source0:	https://github.com/grommunio/gromox/releases/download/gromox-%{version}/gromox-%{version}.tar.zst
Summary:	Groupware server backend for grommunio
URL:		https://github.com/grommunio/gromox
License:	AGPL-3.0
Group:		Servers
BuildRequires:	autoconf automake slibtool make
BuildRequires:	php-devel
BuildRequires:	pkgconfig(wmime)
BuildRequires:	pkgconfig(openssl)
BuildRequires:	pkgconfig(fmt)
BuildRequires:	pkgconfig(libHX)
BuildRequires:	pkgconfig(jsoncpp)
BuildRequires:	pkgconfig(sqlite3)
BuildRequires:	pkgconfig(tinyxml2)
BuildRequires:	pkgconfig(libzstd)
BuildRequires:	pkgconfig(libcurl)
BuildRequires:	pkgconfig(ldap)
BuildRequires:	pkgconfig(mariadb)
BuildRequires:	pkgconfig(libxxhash)
# Optional dependencies for better M$ Exchange emulation support
# ESE = Extensible Storage Engine = Database format for Windows Search, Windows Mail, Exchange, Active Directory
# OLECF = OLE 2 Compound File (some M$ Office files, thumbs.db)
# PFF = Personal Folder File = Outbreak email/contacts/... format https://github.com/libyal/libpff
BuildRequires:	pkgconfig(libesedb)
BuildRequires:	pkgconfig(libolecf)
BuildRequires:	pkgconfig(libpff)

Requires:	%{name}-core = %{EVRD}
Requires:	%{name}-delivery = %{EVRD}
Requires:	%{name}-imap = %{EVRD}
Requires:	%{name}-http = %{EVRD}
Requires:	%{name}-pop3 = %{EVRD}
Requires:	%{name}-tools = %{EVRD}
Requires:	php-gromox = %{EVRD}
Requires:	pam-gromox = %{EVRD}
# M$ compatible mail storage uses windows-1252
Requires:	locales-extra-charsets

%patchlist
gromox-3.5-servicedeps.patch

%description
Gromox is the central groupware server component of grommunio.
It is capable of serving as a drop-in replacement for Microsoft Exchange.
Connectivity options include RPC/HTTP (Outlook Anywhere), MAPI/HTTP,
EWS, IMAP, POP3, an SMTP-speaking LDA, and a PHP module with a MAPI
function subset.

Components can scale-out over multiple hosts.

%package core
Summary:	Core components of the Gromox groupware server
Group:		Servers

%description core
Core components of the Gromox groupware server

%package delivery
Summary:	Components of the Gromox groupware server dealing with mail delivery
Group:		Servers

%description delivery
Components of the Gromox groupware server dealing with mail delivery

%package imap
Summary:	IMAP access component for the Gromox groupware server
Group:		Servers
Requires:	%{name}-core = %{EVRD}

%description imap
IMAP access component for the Gromox groupware server

%package http
Summary:	HTTP/EWS access component for the Gromox groupware server
Group:		Servers
Requires:	%{name}-core = %{EVRD}

%description http
HTTP/EWS access component for the Gromox groupware server

%package pop3
Summary:	POP3 access component for the Gromox groupware server
Group:		Servers
Requires:	%{name}-core = %{EVRD}

%description pop3
POP3 access component for the Gromox groupware server

%package tools
Summary:	Tools for working with the Gromox groupware server
Group:		Servers
Requires:	%{name}-core = %{EVRD}

%description tools
Tools for working with the Gromox groupware server

This contains tools for controlling the server, importing
messages from other servers, and more.

%package -n php-gromox
Summary:	PHP library for interfacing with the Gromox groupware server
Group:		Servers
Requires:	%{name}-core = %{EVRD}

%description -n php-gromox
PHP library for interfacing with the Gromox groupware server

%package -n pam-gromox
Summary:	PAM module for authenticating against the Gromox groupware server's user database
Group:		Servers

%description -n pam-gromox
PAM module for authenticating against the Gromox groupware server's user database

%prep
%autosetup -p1
find . -type f |xargs sed -i 's|/var/lib/gromox|/srv/mail/gromox|g'
export LIBTOOL=slibtool
sed -i -e 's,^pamlibdir =.*,pamlibdir = %{_libdir}/security,' Makefile.am
./qconf --help

%conf
# The libraries are strictly internal - they're
# not meant to be used by anything but gromox
# (and can't be, because the corresponding headers
# aren't installed).
# Let's not pollute the global libdir.
%configure \
	--libdir=%{_libdir}/gromox

%build
%make_build

%install
%make_install
# Let's own the mail store even if it isn't generated by the upstream package
mkdir -p %{buildroot}/srv/mail/gromox

# Replace the php config so we don't necessarily enable MAPI for all php
# instances -- in OpenMandriva, gromox-web gets MAPI through the
# unit files for its own php instance.
cat >%{buildroot}%{_sysconfdir}/php.d/mapi.ini <<'EOF'
; In OpenMandriva, the only known user of the MAPI module,
; gromox-web, uses a custom php instance that loads the
; MAPI extension through other means.
; The MAPI extension is potentially harmful because it
; does not work with opcache and/or JIT enabled.
; If you want to enable the MAPI module for other PHP
; instances, uncomment the following lines (and make
; sure they disable opcache and JIT).
;extension=mapi.so
;mapi.zcore_socket=/run/gromox/zcore.sock
EOF

%files

%files core
# Directories
%dir %{_datadir}/gromox
%dir %{_libexecdir}/gromox
%dir %{_libdir}/gromox
%dir /srv/mail
%dir /srv/mail/gromox
# Metadata indexing
%{_libexecdir}/gromox/midb
%{_unitdir}/gromox-midb.service
%doc %{_mandir}/man8/midb.8gx*
# Messaging bus
%{_libexecdir}/gromox/event
%{_unitdir}/gromox-event.service
%doc %{_mandir}/man8/event.8gx*
# Background worker/cron
%{_libexecdir}/gromox/timer
%{_unitdir}/gromox-timer.service
%doc %{_mandir}/man8/timer.8gx*
# Instance store
%{_libexecdir}/gromox/istore
%{_unitdir}/gromox-istore.service
%doc %{_mandir}/man8/istore.8gx*
# Users, tempfiles etc.
%{_sysusersdir}/sysusers-gromox.conf
%{_tmpfilesdir}/tmpfiles-gromox.conf
# Bounce templates
%{_datadir}/gromox/*_bounce
# Mappings
%{_datadir}/gromox/*.txt
# LDAP schema
%{_datadir}/gromox/gromox.ldif
# SQLite tweaks
%{_datadir}/gromox/sqliterc
# Core libraries
%{_libdir}/gromox/libgxs_mysql_adaptor.so*
%{_libdir}/gromox/libgxs_ruleproc.so*
%{_libdir}/gromox/libgxs_timer_agent.so*
%{_libdir}/gromox/libgxs_event_proxy.so*
%{_libdir}/gromox/libgromox_abtree.so*
%{_libdir}/gromox/libgromox_auth.so*
%{_libdir}/gromox/libgromox_authz.so*
%{_libdir}/gromox/libgromox_common.so*
%{_libdir}/gromox/libgromox_dbop.so*
%{_libdir}/gromox/libgromox_exrpc.so*
%{_libdir}/gromox/libgromox_mh_emsmdb.so*
%{_libdir}/gromox/libgromox_mh_nsp.so*
%{_libdir}/gromox/libgromox_ndr.so*
%{_libdir}/gromox/libgxm_alias_resolve.so*
%{_libdir}/gromox/libgxm_exmdb_local.so*
%{_libdir}/gromox/libgxs_event_stub.so*
%{_libdir}/gromox/libgxs_exmdb_provider.so*
%{_libdir}/gromox/libgxs_midb_agent.so*
# Core data
%{_datadir}/gromox/abkt.pak
%{_datadir}/gromox/timezone.pak
# Cleaner
%{_unitdir}/gromox-cleaner.service
%{_unitdir}/gromox-cleaner.timer
# Autodiscover
%{_libexecdir}/gromox/oxdisco
%{_libdir}/gromox/libgromox_oxdisco.so*
%{_libdir}/gromox/libgromox_mapi.so*
%doc %{_mandir}/man7/autoconfig.7*
%doc %{_mandir}/man7/autodiscover.7*
# Docs
%doc %{_mandir}/man4/mysql_adaptor.4*
%doc %{_mandir}/man4/ldap_adaptor.4*
%doc %{_mandir}/man4/exmdb_local.4*
%doc %{_mandir}/man5/gromox.cfg.5*
%doc %{_mandir}/man7/gromox.7*
%doc %{_mandir}/man4/alias_resolve.4gx*
%doc %{_mandir}/man4/authmgr.4gx*
%doc %{_mandir}/man4/autodiscover.4gx*
%doc %{_mandir}/man4/dnsbl_filter.4gx*
%doc %{_mandir}/man4/event_proxy.4gx*
%doc %{_mandir}/man4/event_stub.4gx*
%doc %{_mandir}/man4/exmdb_provider.4gx*
%doc %{_mandir}/man4/mapi.4gx*
%doc %{_mandir}/man4/mh_emsmdb.4gx*
%doc %{_mandir}/man4/mh_nsp.4gx*
%doc %{_mandir}/man4/midb_agent.4gx*
%doc %{_mandir}/man4/timer_agent.4gx*
%doc %{_mandir}/man4/user_filter.4gx*
%doc %{_mandir}/man5/gromox-selinux.5*
%doc %{_mandir}/man7/mapi.7gx*
%doc %{_mandir}/man8/authtry.8gx*

%files pop3
%{_libexecdir}/gromox/pop3
%{_unitdir}/gromox-pop3.service
%doc %{_mandir}/man8/pop3.8gx*

%files imap
%{_libexecdir}/gromox/imap
%{_unitdir}/gromox-imap.service
%doc %{_mandir}/man8/imap.8gx*

%files http
%{_libdir}/gromox/libgromox_ews.so*
%{_libdir}/gromox/libgromox_emsmdb.so*
%{_libdir}/gromox/libgromox_oab.so*
%{_libdir}/gromox/libgromox_rfr.so*
%{_libdir}/gromox/libgromox_nsp.so*
%{_libexecdir}/gromox/http
%{_unitdir}/gromox-http.service
%doc %{_mandir}/man8/http.8gx*
# zcore (RPC and Protocol Dispatcher for MAPI calls)
%{_libexecdir}/gromox/zcore
%{_unitdir}/gromox-zcore.service
%doc %{_mandir}/man8/zcore.8gx*
# oab = Offline Address Book
%{_libexecdir}/gromox/oab
# Protocol schemas
%{_datadir}/gromox/Messages.xsd
%{_datadir}/gromox/Services.wsdl
%{_datadir}/gromox/Types.xsd
%doc %{_mandir}/man4/ews.4gx*
%doc %{_mandir}/man4/exchange_*.4gx*
%doc %{_mandir}/man4/mod_*.4gx*

%files delivery
%{_libexecdir}/gromox/delivery
%{_libexecdir}/gromox/delivery-queue
%{_libexecdir}/gromox/lda
%{_unitdir}/gromox-delivery.service
%{_unitdir}/gromox-delivery-queue.service
%doc %{_mandir}/man8/delivery.8gx*
%doc %{_mandir}/man8/delivery-queue.8gx*

%files tools
%{_bindir}/gromox-*
# Authentication test
%{_libexecdir}/gromox/authtry
# Database debugger
%{_libexecdir}/gromox/ddbg
%{_libexecdir}/gromox/gromox-snapshot
%{_unitdir}/gromox-snapshot.service
%{_unitdir}/gromox-snapshot.timer
%{_libexecdir}/gromox/kdb-uidextract
%{_libexecdir}/gromox/kdb-uidextract-limited
%{_libexecdir}/gromox/textmapquery
%doc %{_mandir}/man1/ddbg.1gx*
%doc %{_mandir}/man8/cgkrepair.8gx*
%doc %{_mandir}/man8/gromox-*.8*
%doc %{_mandir}/man8/kdb-uidextract.8*
%doc %{_mandir}/man8/kdb-uidextract-limited.8*
%{_datadir}/gromox/gdbinit

%files -n php-gromox
%{_datadir}/gromox/http/php
%{_datadir}/gromox/conf.php
%{_datadir}/gromox/db.php
%{_datadir}/gromox/submit.php
%{_datadir}/gromox/fpm-gromox.conf.sample
%{_sysconfdir}/php.d/mapi.ini
%{_libdir}/php/extensions/mapi.so
%doc %{_mandir}/man4/php-mapi.4*

%files -n pam-gromox
%{_libdir}/security/pam_gromox.so
%doc %{_mandir}/man4/pam_gromox.4gx*
